project_name = "Battery"
version_file = "version.txt"
cmake_path = "battery_cli/build"

[scripts]
build = "cmake --build . && cmake -B {{build_directory}} {{cmake_flags}}"
#test = "gtest"
#run = "./battery"
#configure = ["cmake",  "..", "-DCONFIG=Release"]
test = "echo Hello this is a test"