project_name = "Battery"
version_file = "version.txt"
cmake_path = "battery_cli/build"

[scripts]
#build = ["cmake", "--build", "."]
#test = "gtest"
#run = "./battery"
#configure = ["cmake",  "..", "-DCONFIG=Release"]