#pragma once

enum class Error {
    INTERNAL_ERROR = 1,
    TERMINATED_BY_USER,
    NOT_YET_IMPLEMENTED,
    CLI_FAILED_TO_PARSE,
    PROJECT_FILE_NOT_FOUND,
    VERSION_FILE_NOT_FOUND,
    PROJECT_FILE_INVALID,
    INVALID_VERSION,
    TOML_PARSE_ERROR,
    SCRIPT_NOT_FOUND,
    SCRIPT_PARSE_ERROR,
    SCRIPT_FAILED,
    FILE_WRITE_ERROR,
    FILE_NOT_FOUND_ERROR,
    EXECUTABLE_NOT_FOUND
};
